parameters:
    Drupal8Rector\Rector\CodeStyle\PropertyNameVariableNameRector:
        # Snake cased property names should not be changed in entity types
        # because those are mapped to snake cased keys in entity
        # annotations.
        - Drupal\Core\Entity\Annotation\EntityType
        - Drupal\Core\Entity\EntityType

# Set of EXPERIMENTAL rectors, use them on your own risk!
services:
    Drupal8Rector\Rector\CodeStyle\PropertyNameVariableNameRector:
        arguments: ['%Drupal8Rector\Rector\CodeStyle\PropertyNameVariableNameRector%']
