# Contains automatic fixes for some deprecations introduced before Drupal 8.7.
services:
    Rector\Rector\MethodCall\MethodNameReplacerRector:
        Drupal\Core\Entity\EntityInterface:
            url: toUrl
            urlInfo: toUrl
            link: toLink
        Drupal\Core\Entity\Entity:
            # Note, you may need the "entity_field.manager" service instead of
            # entity_type.manager.
            entityManager: entityTypeManager
        Drupal\Core\Controller\ControllerBase:
            # Note, you may need the "entity_field.manager" service instead of
            # entity_type.manager.
            entityManager: entityTypeManager

    Mxr576\Rector\Deprecation\UrlGeneratorTraitRector: ~
