# Contains automatic fixes for some deprecations introduced in Drupal 8.0.
services:
  DrupalRector\Rector\Deprecation\EntityManagerRector: ~
  DrupalRector\Rector\Deprecation\DBInsertRector: ~
  DrupalRector\Rector\Deprecation\DBSelectRector: ~
  DrupalRector\Rector\Deprecation\DBQueryRector: ~
  DrupalRector\Rector\Deprecation\DBDeleteRector: ~
  DrupalRector\Rector\Deprecation\DBUpdateRector: ~
  DrupalRector\Rector\Deprecation\DrupalRenderRector: ~
  DrupalRector\Rector\Deprecation\DrupalRenderRootRector: ~
  DrupalRector\Rector\Deprecation\DrupalURLRector: ~
  DrupalRector\Rector\Deprecation\FormatDateRector: ~
  DrupalRector\Rector\Deprecation\DrupalLRector: ~
  DrupalRector\Rector\Deprecation\EntityInterfaceUrlInfoRector: ~
  DrupalRector\Rector\Deprecation\EntityLoadRector: ~
  DrupalRector\Rector\Deprecation\FileLoadRector: ~
  DrupalRector\Rector\Deprecation\NodeLoadRector: ~
