# Contains automatic fixes for some deprecations introduced in Drupal 8.6.
services:
  DrupalRector\Rector\Deprecation\UnicodeStrLenRector: ~
  DrupalRector\Rector\Deprecation\UnicodeStrtolowerRector: ~
  DrupalRector\Rector\Deprecation\UnicodeSubStrRector: ~
