name: drupal_rector

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_with_drupal:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # Install latest Drupal
                    mkdir drupal-rector07
                    composer create-project drupal/recommended-project drupal-rector07 --dev --no-progress

                    # Install drupal-rector (based on rector 0.7.x)
                    cd drupal-rector07
                    composer require palantirnet/drupal-rector:dev-rector-0.7 --no-progress

                    # Prepare rector config files with Drupal specific settings
                    cp vendor/palantirnet/drupal-rector/rector.yml .

                    # Prepare rector_examples folder in the drupal modules directory
                    mkdir -p web/modules/custom
                    cp -r vendor/palantirnet/drupal-rector/rector_examples web/modules/custom/.

                    # Run Rector
                    vendor/bin/rector process web/modules/custom/rector_examples --dry-run
