name: legacy_drupal_check_conflict

on:
    pull_request: null
    push: null

jobs:
    legacy_drupal_check_conflict:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # Download the latest Drupal core project and all its dependencies
                    composer create-project drupal/recommended-project drupal --dev --no-progress

            -   run: |
                    # Install legacy-drupal-check version 1.0.14 (when it required phpstan 0.11)
                    cd drupal
                    composer require mglaman/drupal-check:1.0.14 --dev

            -   run: |
                    # Attempt installing drupal-rector (should fail because it requires phpstan 0.12)
                    cd drupal
                    composer require palantirnet/drupal-rector --dev
